name: New PR Workflow
run-name: ${{ github.actor }} just raised a PR on Polygon Tokenlists

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  Tests:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      - name: CHECK OUT REPOSITORY
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check Ubuntu Version
        run: lsb_release -a

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Tokenlists
        run: npm run build
